version: '3'
services:
   postgres:
      container_name: psql
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - 5432:5432
      environment:
         POSTGRES_USER: docker
         POSTGRES_PASSWORD: docker
         POSTGRES_DB: docker
