version: '3.3'
services:
   jenkins-data:
      container_name: jenkins-data
      build:
         context: ./Jenkins
         dockerfile: Dockerfile-data

   jenkins:
      container_name: jenkins
      networks: 
         - frontend
      restart: always
      build:
         context: ./Jenkins
         dockerfile: Dockerfile
      ports:
         - 8081:8080
         - 50000:50000
      volumes:
         - jenkins-data
   gitbucket:
      container_name: gitbucket
      image: f99aq8ove/gitbucket
      networks: 
        - frontend
      ports:
         - 8082:8080
         - 29418:29418
      restart: always
      volumes:
         - /data/gitbucket:/gitbucket
   wildfly:
      container_name: wildfly
      build: 
         context: ./Wildfly
         dockerfile: Dockerfile
      ports:
          - 8080:8080
          - 9990:9990
      networks:
          - backend
   postgres:
      container_name: db
      image: postgres:9.6
      restart: always
      ports:
         - 5432:5432
      environment:
         POSTGRES_USER: docker
         POSTGRES_PASSWORD: docker
         POSTGRES_DB: docker
      volumes:
         - /data/postgres:/var/lib/postgresql/data
networks:
   frontend:
   backend:
